# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fast_form.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(674, 185)
        Form.setWindowOpacity(0.95)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditPath = QtWidgets.QLineEdit(Form)
        self.lineEditPath.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPath.sizePolicy().hasHeightForWidth())
        self.lineEditPath.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tlwg Typo")
        font.setPointSize(12)
        self.lineEditPath.setFont(font)
        self.lineEditPath.setFrame(True)
        self.lineEditPath.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditPath.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditPath.setDragEnabled(False)
        self.lineEditPath.setObjectName("lineEditPath")
        self.gridLayout.addWidget(self.lineEditPath, 0, 1, 1, 4)
        self.labelInfo = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelInfo.sizePolicy().hasHeightForWidth())
        self.labelInfo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tlwg Typo")
        font.setPointSize(12)
        self.labelInfo.setFont(font)
        self.labelInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInfo.setObjectName("labelInfo")
        self.gridLayout.addWidget(self.labelInfo, 2, 2, 1, 2)
        self.labelShortInfo = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelShortInfo.sizePolicy().hasHeightForWidth())
        self.labelShortInfo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tlwg Typo")
        font.setPointSize(12)
        self.labelShortInfo.setFont(font)
        self.labelShortInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelShortInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelShortInfo.setObjectName("labelShortInfo")
        self.gridLayout.addWidget(self.labelShortInfo, 1, 2, 1, 2)
        self.barProgress = QtWidgets.QProgressBar(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barProgress.sizePolicy().hasHeightForWidth())
        self.barProgress.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tlwg Typo")
        font.setPointSize(12)
        self.barProgress.setFont(font)
        self.barProgress.setMinimum(0)
        self.barProgress.setMaximum(4)
        self.barProgress.setProperty("value", 0)
        self.barProgress.setTextVisible(True)
        self.barProgress.setOrientation(QtCore.Qt.Horizontal)
        self.barProgress.setInvertedAppearance(False)
        self.barProgress.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.barProgress.setObjectName("barProgress")
        self.gridLayout.addWidget(self.barProgress, 4, 1, 1, 4)
        self.buttonExit = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonExit.sizePolicy().hasHeightForWidth())
        self.buttonExit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tlwg Typo")
        font.setPointSize(12)
        self.buttonExit.setFont(font)
        self.buttonExit.setObjectName("buttonExit")
        self.gridLayout.addWidget(self.buttonExit, 2, 4, 1, 1)
        self.buttonPath = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPath.sizePolicy().hasHeightForWidth())
        self.buttonPath.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tlwg Typo")
        font.setPointSize(12)
        self.buttonPath.setFont(font)
        self.buttonPath.setObjectName("buttonPath")
        self.gridLayout.addWidget(self.buttonPath, 1, 1, 1, 1)
        self.buttonStart = QtWidgets.QPushButton(Form)
        self.buttonStart.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonStart.sizePolicy().hasHeightForWidth())
        self.buttonStart.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tlwg Typo")
        font.setPointSize(12)
        self.buttonStart.setFont(font)
        self.buttonStart.setCheckable(False)
        self.buttonStart.setChecked(False)
        self.buttonStart.setObjectName("buttonStart")
        self.gridLayout.addWidget(self.buttonStart, 1, 4, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Java to Jar (Executable) Package Converter"))
        self.lineEditPath.setText(_translate("Form", "example path >> /com/company/Main.java"))
        self.labelInfo.setText(_translate("Form", "select path => start"))
        self.labelShortInfo.setText(_translate("Form", "[INFO]"))
        self.barProgress.setFormat(_translate("Form", "%p%"))
        self.buttonExit.setText(_translate("Form", "Quit"))
        self.buttonPath.setText(_translate("Form", "select path"))
        self.buttonStart.setText(_translate("Form", "Start"))
